[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/save-contact"
  to = "/.netlify/functions/save-contact"
  status = 200

[[redirects]]
  from = "/api/download-contacts"
  to = "/.netlify/functions/save-contact"
  status = 200